#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

sudo apt update && sudo apt install -y gh nodejs npm

python3 -m pip install --upgrade pip -r requirements.txt
sudo npm install -g concurrently
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo BINDIR=/usr/local/bin bash
pre-commit install
